name: Test

on: [push]
jobs:
  test:
    #where to run
    runs-on: ubuntu-latest
    #steps to be done
    steps:
      #download repository
      - uses: actions/checkout@v4
        #java setup
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: Xotabu4/selenoid-github-action@v2
      #run tests
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub
      #download tests history
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      #generate report
      - uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      #public report
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history